### ISSUE TITLE
Bot doesn't respond to /configure command after Heroku install

### ISSUE THREAD

**Issue by tallzilla** [DMcP89/harambot#105]
**Describe the bug**
Hi there. I just went through the Heroku deployment workflow to install the service, pasted Yahoo and Discord credentials into the appropriate fields, etc.. When I add the bot to my league's discord, my logs look normal:

```
2023-08-03T19:51:25.121316+00:00 app[worker.1]: Requirement already satisfied: yahoo-oauth==2.0 in ./.heroku/python/lib/python3.11/site-packages (from -r requirements.txt (line 54)) (2.0)
2023-08-03T19:51:25.123776+00:00 app[worker.1]: Requirement already satisfied: yarl==1.8.1 in ./.heroku/python/lib/python3.11/site-packages (from -r requirements.txt (line 55)) (1.8.1)
2023-08-03T19:51:29.879002+00:00 app[worker.1]: [2023-08-03 19:51:29] [INFO    ] discord.client: logging in using static token
2023-08-03T19:51:30.264395+00:00 app[worker.1]: [2023-08-03 19:51:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f1adaa0aab91ad13a89549deacf8477f).
2023-08-03T19:51:32.285216+00:00 app[worker.1]: [2023-08-03 19:51:32,285 INFO] [harambot.py.bot.on_ready] Everything's all ready to go~
2023-08-03T19:51:32.285791+00:00 app[worker.1]: [2023-08-03 19:51:32,285 INFO] [/app/harambot/cogs/webserver.py.webserver.webserver] Webserver started on port 6838
2023-08-03T19:52:11.895656+00:00 app[worker.1]: [2023-08-03 19:52:11,895 INFO] [harambot.py.bot.on_guild_join] Joined Bill's Professional Football Server
2023-08-03T19:52:11.899240+00:00 app[worker.1]: [2023-08-03 19:52:11,899 INFO] [harambot.py.bot.on_guild_join] Guild not configured!

```
I created a bot invite link: https://discord.com/oauth2/authorize?client_id=XXX&permissions=277025505344&scope=bot

And discord adds the bot and I am prompted to give a configure command

```
Harambot
BOT
 — Today at 12:52 PM
Thank you for adding Harambot to your server!
        Please complete your setup by running the /configure command!
```
However, when I send back the /configure command, I receive no further prompt from the bot:

![image](https://github.com/DMcP89/harambot/assets/1684112/f2950749-32f7-45a6-9bdf-60e035e25a1d)

**To Reproduce**
1. Followed the Heroku installation workflow through https://heroku.com/deploy
2. Installed the Yahoo App per instructions
3. Installed the Discord bot per instructions
4. Get an initial DM from the discord bot, and log lines in the heroku instance saying Guild not configured
5. (a few times) Tried uninstalling the heroku app, restarting, etc..

**Expected behavior**
Expect sending /configure to the bot to give me a prompt to configure the guild as described in your installation instructions

**Screenshots**
See Above

**Comment by vanzanttt** [comment]
Just wanted to second this ^ I tried setting this up yesterday and ran into the exact same problem.

**Comment by DMcP89** [comment]
I think the Heroku deployment might still be using an older version of the bot. I need to migrate it to use the docker image. Add this to the next release.

**Comment by DMcP89** [comment]
@tallzilla @vanzanttt any chance one of you could add me as a contributor to your Heroku project so I can troubleshoot a bit?

**Comment by tallzilla** [comment]
Done. Used your github public email address.

**Comment by DMcP89** [comment]
@tallzilla can you use this one instead? dmcp89@gmail.com

**Comment by tallzilla** [comment]
Done

**Comment by tallzilla** [comment]
Hi there. I tried using render instead of heroku to try to get to a working bot before the start of my league's NFL season. I'm getting the same issue with render as heroku. I setup the server with the discord + yahoo keys, etc. etc., added the bot to my league's discord. The bot was added successfully to Discord, the render server appears to be connected, but the bot doesn't respond to the /configure command...

Maybe I am messing up the discord bot configuration somehow? Let me know if there is more debugging info I can provide.

(Render log posted below)

```
Sep 9 08:30:30 AM  Starting service...
Sep 9 08:31:32 AM  [2023-09-09 15:31:32] [INFO    ] discord.client: logging in using static token
Sep 9 08:31:33 AM  [2023-09-09 15:31:33] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 18a8f32614d515d63baaf8ebac20782b).
Sep 9 08:31:35 AM  [2023-09-09 15:31:35,679 INFO] [/usr/local/lib/python3.10/site-packages/harambot/cogs/webserver.py.webserver.webserver] Webserver started on port 10000
Sep 9 08:31:36 AM  [2023-09-09 15:31:36,141 INFO] [harambot.py.bot.on_ready] Everything's all ready to go~
Sep 9 08:31:44 AM  Your service is live 🎉
Sep 9 08:31:45 AM  ==> Detected service running on port 10000
Sep 9 08:31:45 AM  ==> Docs on specifying a port: https://render.com/docs/web-services#port-detection
Sep 9 08:35:26 AM  [2023-09-09 15:35:26,193 INFO] [harambot.py.bot.on_guild_join] Joined Bill's Professional Football Server
Sep 9 08:35:26 AM  [2023-09-09 15:35:26,259 INFO] [harambot.py.bot.on_guild_join] Guild not configured!
```

**Comment by tallzilla** [comment]
Hi there. I tried using render instead of heroku to try to get to a working bot before the start of my league's NFL season. I'm getting the same issue with render as heroku. I setup the server with the discord + yahoo keys, etc. etc., added the bot to my league's discord. The bot was added successfully to Discord, the render server appears to be connected, but the bot doesn't respond to the /configure command...

Maybe I am messing up the discord bot configuration somehow? Let me know if there is more debugging info I can provide.

```
(Render log posted below)

Sep 9 08:30:30 AM  Starting service...
Sep 9 08:31:32 AM  [2023-09-09 15:31:32] [INFO    ] discord.client: logging in using static token
Sep 9 08:31:33 AM  [2023-09-09 15:31:33] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 18a8f32614d515d63baaf8ebac20782b).
Sep 9 08:31:35 AM  [2023-09-09 15:31:35,679 INFO] [/usr/local/lib/python3.10/site-packages/harambot/cogs/webserver.py.webserver.webserver] Webserver started on port 10000
Sep 9 08:31:36 AM  [2023-09-09 15:31:36,141 INFO] [harambot.py.bot.on_ready] Everything's all ready to go~
Sep 9 08:31:44 AM  Your service is live 🎉
Sep 9 08:31:45 AM  ==> Detected service running on port 10000
Sep 9 08:31:45 AM  ==> Docs on specifying a port: https://render.com/docs/web-services#port-detection
Sep 9 08:35:26 AM  [2023-09-09 15:35:26,193 INFO] [harambot.py.bot.on_guild_join] Joined Bill's Professional Football Server
Sep 9 08:35:26 AM  [2023-09-09 15:35:26,259 INFO] [harambot.py.bot.on_guild_join] Guild not configured!
```

**Comment by tallzilla** [comment]
Accidentally closed issue... reopning.

**Comment by tallzilla** [comment]
Actually, disregard the comment about render... that workflow appears to get past the /configure command...

**Comment by DMcP89** [comment]
@tallzilla okay so just so I'm clear Heroku is the only place you faced this issue?

**Comment by tallzilla** [comment]
Yes, that's it.

**Comment by DMcP89** [comment]
@tallzilla @vanzanttt FYI, I have decided to remove Heroku support from this project. Heroku has removed its free tier and they force you to use their container registry if you want to deploy using a docker image. 

See #140
