### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by jpz8792** [DMcP89/harambot#110]
I found your post on reddit here: https://www.reddit.com/r/fantasyfootball/comments/15ni3r5/harambot_031_beta_discord_bot_for_yahoo_fantasy/

If we add the bot to our own server that you're hosting on Render, does that mean we can skip all the prerequisite steps in your wiki?

I believe I configured it properly, but no commands are showing up. I also saw a comment on your post about restarting the bot. Is that something we can do or something you have to do?

Thanks!

**Comment by DMcP89** [comment]
Hi @jpz8792 

Thanks for testing out the bot! If you've added the bot I have running on render the only thing you have to do is run the config command.

Regarding the missing commands, yes there's currently an issue with the bot where anytime a new server adds the bot I have to restart it. I've been restarting the bot once a night so by tomorrow you should see the commands. Currently working on a fix.
