### ISSUE TITLE
Heroku deployment issues with 0.2.0-Beta

### ISSUE THREAD

**Issue by sassyass** [DMcP89/harambot#61]
**Describe the bug**
the bot was deployed to heroku, added to the discord server, and successfully configured. however, it is not responding to any bot commands.

**To Reproduce**
1. issued a command such as "$standings", no response

**Expected behavior**

response from the bot commands.

**logs from Heroku bot**

```
> `2022-10-02T18:52:39.486349+00:00 app[worker.1]: [2022-10-02 18:52:39] [ERROR   ] discord.client: Ignoring exception in on_message
> 2022-10-02T18:52:39.486356+00:00 app[worker.1]: Traceback (most recent call last):
> 2022-10-02T18:52:39.486357+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/peewee.py", line 7024, in get
> 2022-10-02T18:52:39.486357+00:00 app[worker.1]:     return clone.execute(database)[0]
> 2022-10-02T18:52:39.486358+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/peewee.py", line 4389, in __getitem__
> 2022-10-02T18:52:39.486358+00:00 app[worker.1]:     return self.row_cache[item]
> 2022-10-02T18:52:39.486359+00:00 app[worker.1]: IndexError: list index out of range
> 2022-10-02T18:52:39.486359+00:00 app[worker.1]: 
> 2022-10-02T18:52:39.486360+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
> 2022-10-02T18:52:39.486360+00:00 app[worker.1]: 
> 2022-10-02T18:52:39.486360+00:00 app[worker.1]: Traceback (most recent call last):
> 2022-10-02T18:52:39.486361+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
> 2022-10-02T18:52:39.486361+00:00 app[worker.1]:     await coro(*args, **kwargs)
> 2022-10-02T18:52:39.486362+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1392, in on_message
> 2022-10-02T18:52:39.486362+00:00 app[worker.1]:     await self.process_commands(message)
> 2022-10-02T18:52:39.486363+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1389, in process_commands
> 2022-10-02T18:52:39.486363+00:00 app[worker.1]:     await self.invoke(ctx)  # type: ignore
> 2022-10-02T18:52:39.486363+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
> 2022-10-02T18:52:39.486364+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
> 2022-10-02T18:52:39.486364+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 978, in invoke
> 2022-10-02T18:52:39.486364+00:00 app[worker.1]:     await self.prepare(ctx)
> 2022-10-02T18:52:39.486365+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 897, in prepare
> 2022-10-02T18:52:39.486365+00:00 app[worker.1]:     await self.call_before_hooks(ctx)
> 2022-10-02T18:52:39.486365+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ext/commands/core.py", line 843, in call_before_hooks
> 2022-10-02T18:52:39.486365+00:00 app[worker.1]:     await hook(ctx)
> 2022-10-02T18:52:39.486366+00:00 app[worker.1]:   File "/app/harambot/cogs/yahoo.py", line 30, in cog_before_invoke
> 2022-10-02T18:52:39.486366+00:00 app[worker.1]:     guild = Guild.get(Guild.guild_id == str(ctx.guild.id))
> 2022-10-02T18:52:39.486367+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/peewee.py", line 6576, in get
> 2022-10-02T18:52:39.486367+00:00 app[worker.1]:     return sq.get()
> 2022-10-02T18:52:39.486367+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/peewee.py", line 7027, in get
> 2022-10-02T18:52:39.486367+00:00 app[worker.1]:     raise self.model.DoesNotExist('%s instance matching query does '
> 2022-10-02T18:52:39.486368+00:00 app[worker.1]: database.models.GuildDoesNotExist: <Model: Guild> instance matching query does not exist:
> 2022-10-02T18:52:39.486369+00:00 app[worker.1]: SQL: SELECT "t1"."id", "t1"."guild_id", "t1"."access_token", "t1"."refresh_token", "t1"."expires_in", "t1"."token_type", "t1"."xoauth_yahoo_guid", "t1"."token_time", "t1"."league_id", "t1"."league_type", "t1"."RIP_text", "t1"."RIP_image_url" FROM "guild" AS "t1" WHERE ("t1"."guild_id" = %s) LIMIT %s OFFSET %s
> 2022-10-02T18:52:39.486370+00:00 app[worker.1]: Params: ['842247078146474025', 1, 0]
```

**Comment by DMcP89** [comment]
@sassyass  can you check the guilds table of your db to see if there is a record for your guild in it?

**Comment by sassyass** [comment]
how do i do that, sorry? was i supposed to create that in the deployment?

**Comment by DMcP89** [comment]
The database gets created automatically by heroku and the bot will make the table on the fly if it does not already exist. 

Can you run the configure command and paste the log output after reconfiguring?

**Comment by DMcP89** [comment]
@sassyass would you be willing to share your heroku deployment with me? Under Access you can add me as a collaborator:

![image](https://user-images.githubusercontent.com/4146149/193869854-41c38b82-055d-4ba5-b728-7e7988dba908.png)

dmcp89@gmail.com

**Comment by sassyass** [comment]
ok

**Comment by DMcP89** [comment]
Okay, I have found the issue. 

For some reason the yahoo api is not returning a xoauth_yahoo_guid value when your bot makes its authorization request. This appears to be the norm for new yahoo api applications. 

Will get to work on a fix.

**Comment by DMcP89** [comment]
@sassyass  I have merged a fix for this to the [release/0.2.1-Beta](https://github.com/DMcP89/harambot/tree/release/0.2.1-Beta) branch. Can you try the following:

1. Kick your bot from your guild
2. Delete your heroku app
3. Redeploy the heroku app using [release/0.2.1-Beta](https://github.com/DMcP89/harambot/tree/release/0.2.1-Beta) branch
4. Add the bot back to your guild

**Comment by sassyass** [comment]
why i try to deploy heroku complains "No app.json located in the repo URL provided."

**Comment by wontu12** [comment]
same here

**Comment by sassyass** [comment]
that looks like it worked, thanks!

**Comment by sassyass** [comment]
question: do i need to turn on the dyno in heroku? i assumed the answer was yes so i did, but it wasn't in the instructions

**Comment by wontu12** [comment]
@DMcP89 it worked more than before :) 

but now I'm not sure what happened where I was configuring it in discord messages and when asked for the image URL it didn't respond to that. and it doesn't seem to respond to commands or /configure

**Comment by DMcP89** [comment]
@wontu12  could you invite me to your discord guild as well? Will be easier to troubleshoot if I can test commands

**Comment by wontu12** [comment]
@DMcP89 ya sure, heres link ill add you to a test channel: https://discord.gg/tmjpvfBp

**Comment by SamB-github** [comment]
> 

I also can run configure with the bot in guild. It accepts replies (in configure PM) until I send the image link and then does nothing. It does not reply to any commands other than the configure. Deleting and configuring on heroku and discord do not solve the problem.

**Comment by DMcP89** [comment]
@SamB-github  can you add me as a contributor to your heroku app and I will take a look?

**Comment by SamB-github** [comment]
> 

I have added you.

**Comment by DMcP89** [comment]
@SamB-github  can you add me to your discord server as well so I can run some tests?

**Comment by SamB-github** [comment]
> @SamB-github can you add me to your discord server as well so I can run some tests?

The configure worked today when I used it from the channel. All commands are also now working. Thanks for your help.

**Comment by Nakisiza** [comment]
I was having problems with the Bot not replying back when giving it permission. After deploying on Heroku with 0.2.1, it now works. Only issues i found were:

1. After asking for the URL for the pic to be used in $RIP, it does not reply back and the command does not work.
2. /configure doesn't show up as a command nor works.

**Comment by DMcP89** [comment]
@Nakisiza can you add me to your heroku app as a contributor? If you can add me to your discord server as well that would help too.

**Comment by Nakisiza** [comment]
@DMcP89 no prob. i can do that later today.

**Comment by DMcP89** [comment]
@Nakisiza  Any update? Not seeing your bot in my list or heroku apps.

**Comment by DMcP89** [comment]
Going to close this issue and merge the 0.2.1-Beta branch and cut a new release. @Nakisiza  if you are still having issues with the bot please open a new issue and we can troubleshoot there.

**Comment by Nakisiza** [comment]
@DMcP89ready to add you as a collaborator. What email should i use?
