### ISSUE TITLE
Think I'm missing a step

### ISSUE THREAD

**Issue by wontu12** [DMcP89/harambot#62]
I followed the directions step by step, but once I added the bot to my Discord server, it didn't message me directly to be set up. It also shows as offline in the Discord server. 

I also get this issue on Heroku: 

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

I'm not a developer, so I'm not sure what to troubleshoot here. Can you help? Thanks!

**Comment by sassyass** [comment]
i ran into the same thing: when you set up the bot you need to turn on the Priviledged Gateway Intents

![image](https://user-images.githubusercontent.com/15484580/193476289-7e1dbb33-d6a8-4d6c-be95-191d014a380b.png)

**Comment by wontu12** [comment]
> i ran into the same thing: when you set up the bot you need to turn on the Priviledged Gateway Intents
> 
> ![image](https://user-images.githubusercontent.com/15484580/193476289-7e1dbb33-d6a8-4d6c-be95-191d014a380b.png)

thanks! just tried this out and then re-added the bot (since nothing happened immediately) and nothing happened. am I missing something else maybe?

**Comment by DMcP89** [comment]
@wontu12  I would be you're running into the same issue @sassyass  is in issue #61, let's continue this discussion there.

@sassyass  Do you mind if I use these screenshots to update the readme?

**Comment by sassyass** [comment]
sure, go ahead

**Comment by wontu12** [comment]
sounds good, although it seems like their bot was able to be configured. mine was added to my discord server, but I wasn't able to do the next steps. is this still the same issue then?
