### ISSUE TITLE
Simplify the configuration procedure

### ISSUE THREAD

**Issue by DMcP89** [DMcP89/harambot#63]
Even with the bot now handling configuration, it is still a bit clunky and error-prone. Need to streamline this process.

**Comment by izzymang** [comment]
Hi - I deployed on Heroku and added to my Discord server, but it still hasn't messaged me to complete the setup and add the Yahoo League ID. How long does it take before it should message me?

**Comment by DMcP89** [comment]
Having mods be able to configure the bot would be useful I think for larger guilds. I will open an enhancement for adding that support.
